/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedPapierkorbRouteImport } from './routes/_authenticated/papierkorb'
import { Route as AuthenticatedKlassenIndexRouteImport } from './routes/_authenticated/klassen.index'
import { Route as AuthenticatedKlassenIdRouteImport } from './routes/_authenticated/klassen.$id'
import { Route as AuthenticatedRaeumeIndexRouteImport } from './routes/_authenticated/raeume.index'
import { Route as AuthenticatedRaeumeIdRouteImport } from './routes/_authenticated/raeume.$id'
import { Route as AuthenticatedSitzplaeneIndexRouteImport } from './routes/_authenticated/sitzplaene.index'
import { Route as AuthenticatedSitzplaeneIdRouteImport } from './routes/_authenticated/sitzplaene.$id'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPapierkorbRoute = AuthenticatedPapierkorbRouteImport.update({
  id: '/_authenticated/papierkorb',
  path: '/papierkorb',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedKlassenIndexRoute =
  AuthenticatedKlassenIndexRouteImport.update({
    id: '/_authenticated/klassen/',
    path: '/klassen/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedKlassenIdRoute = AuthenticatedKlassenIdRouteImport.update({
  id: '/_authenticated/klassen/$id',
  path: '/klassen/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRaeumeIndexRoute =
  AuthenticatedRaeumeIndexRouteImport.update({
    id: '/_authenticated/raeume/',
    path: '/raeume/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedRaeumeIdRoute = AuthenticatedRaeumeIdRouteImport.update({
  id: '/_authenticated/raeume/$id',
  path: '/raeume/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSitzplaeneIndexRoute =
  AuthenticatedSitzplaeneIndexRouteImport.update({
    id: '/_authenticated/sitzplaene/',
    path: '/sitzplaene/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSitzplaeneIdRoute =
  AuthenticatedSitzplaeneIdRouteImport.update({
    id: '/_authenticated/sitzplaene/$id',
    path: '/sitzplaene/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/papierkorb': typeof AuthenticatedPapierkorbRoute
  '/': typeof AuthenticatedIndexRoute
  '/klassen/$id': typeof AuthenticatedKlassenIdRoute
  '/raeume/$id': typeof AuthenticatedRaeumeIdRoute
  '/sitzplaene/$id': typeof AuthenticatedSitzplaeneIdRoute
  '/klassen/': typeof AuthenticatedKlassenIndexRoute
  '/raeume/': typeof AuthenticatedRaeumeIndexRoute
  '/sitzplaene/': typeof AuthenticatedSitzplaeneIndexRoute
}
export interface FileRoutesByTo {
  '/papierkorb': typeof AuthenticatedPapierkorbRoute
  '/': typeof AuthenticatedIndexRoute
  '/klassen/$id': typeof AuthenticatedKlassenIdRoute
  '/raeume/$id': typeof AuthenticatedRaeumeIdRoute
  '/sitzplaene/$id': typeof AuthenticatedSitzplaeneIdRoute
  '/klassen': typeof AuthenticatedKlassenIndexRoute
  '/raeume': typeof AuthenticatedRaeumeIndexRoute
  '/sitzplaene': typeof AuthenticatedSitzplaeneIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/papierkorb': typeof AuthenticatedPapierkorbRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/klassen/$id': typeof AuthenticatedKlassenIdRoute
  '/_authenticated/raeume/$id': typeof AuthenticatedRaeumeIdRoute
  '/_authenticated/sitzplaene/$id': typeof AuthenticatedSitzplaeneIdRoute
  '/_authenticated/klassen/': typeof AuthenticatedKlassenIndexRoute
  '/_authenticated/raeume/': typeof AuthenticatedRaeumeIndexRoute
  '/_authenticated/sitzplaene/': typeof AuthenticatedSitzplaeneIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/papierkorb'
    | '/'
    | '/klassen/$id'
    | '/raeume/$id'
    | '/sitzplaene/$id'
    | '/klassen/'
    | '/raeume/'
    | '/sitzplaene/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/papierkorb'
    | '/'
    | '/klassen/$id'
    | '/raeume/$id'
    | '/sitzplaene/$id'
    | '/klassen'
    | '/raeume'
    | '/sitzplaene'
  id:
    | '__root__'
    | '/_authenticated/papierkorb'
    | '/_authenticated/'
    | '/_authenticated/klassen/$id'
    | '/_authenticated/raeume/$id'
    | '/_authenticated/sitzplaene/$id'
    | '/_authenticated/klassen/'
    | '/_authenticated/raeume/'
    | '/_authenticated/sitzplaene/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedPapierkorbRoute: typeof AuthenticatedPapierkorbRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedKlassenIdRoute: typeof AuthenticatedKlassenIdRoute
  AuthenticatedRaeumeIdRoute: typeof AuthenticatedRaeumeIdRoute
  AuthenticatedSitzplaeneIdRoute: typeof AuthenticatedSitzplaeneIdRoute
  AuthenticatedKlassenIndexRoute: typeof AuthenticatedKlassenIndexRoute
  AuthenticatedRaeumeIndexRoute: typeof AuthenticatedRaeumeIndexRoute
  AuthenticatedSitzplaeneIndexRoute: typeof AuthenticatedSitzplaeneIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/papierkorb': {
      id: '/_authenticated/papierkorb'
      path: '/papierkorb'
      fullPath: '/papierkorb'
      preLoaderRoute: typeof AuthenticatedPapierkorbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/klassen/': {
      id: '/_authenticated/klassen/'
      path: '/klassen'
      fullPath: '/klassen/'
      preLoaderRoute: typeof AuthenticatedKlassenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/klassen/$id': {
      id: '/_authenticated/klassen/$id'
      path: '/klassen/$id'
      fullPath: '/klassen/$id'
      preLoaderRoute: typeof AuthenticatedKlassenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/raeume/': {
      id: '/_authenticated/raeume/'
      path: '/raeume'
      fullPath: '/raeume/'
      preLoaderRoute: typeof AuthenticatedRaeumeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/raeume/$id': {
      id: '/_authenticated/raeume/$id'
      path: '/raeume/$id'
      fullPath: '/raeume/$id'
      preLoaderRoute: typeof AuthenticatedRaeumeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sitzplaene/': {
      id: '/_authenticated/sitzplaene/'
      path: '/sitzplaene'
      fullPath: '/sitzplaene/'
      preLoaderRoute: typeof AuthenticatedSitzplaeneIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sitzplaene/$id': {
      id: '/_authenticated/sitzplaene/$id'
      path: '/sitzplaene/$id'
      fullPath: '/sitzplaene/$id'
      preLoaderRoute: typeof AuthenticatedSitzplaeneIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedPapierkorbRoute: AuthenticatedPapierkorbRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedKlassenIdRoute: AuthenticatedKlassenIdRoute,
  AuthenticatedRaeumeIdRoute: AuthenticatedRaeumeIdRoute,
  AuthenticatedSitzplaeneIdRoute: AuthenticatedSitzplaeneIdRoute,
  AuthenticatedKlassenIndexRoute: AuthenticatedKlassenIndexRoute,
  AuthenticatedRaeumeIndexRoute: AuthenticatedRaeumeIndexRoute,
  AuthenticatedSitzplaeneIndexRoute: AuthenticatedSitzplaeneIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
